foodgram/urls.py
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

from foodgram import settings

handler404 = "foodgram.views.page_not_found"
handler500 = "foodgram.views.server_error"

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
]

urlpatterns += [
    path('about-author/', views.flatpage, {'url': '/about-author/'},
         name='about_author'),
    path('about-tech/', views.flatpage, {'url': '/about-tech/'},
         name='about_tech'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL)

recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("author/<str:author>/", views.author_recipes, name="author_recipes"),

    path("follows/<str:username>/", views.my_follow, name="my_follows"),

    path("recipes/<int:recipe_id>/", views.recipe_view, name="recipe_view"),
    path("recipe/delete/<int:recipe_id>/", views.delete_recipe,
         name="delete_recipe"),
    path("recipe/new/", views.new_recipe, name="new_recipe"),
    path("recipe/change/<int:recipe_id>/", views.change_recipe,
         name="change_recipe"),

    path("favorite/", views.favorite, name="favorite"),
    path("favorites/", views.add_favorites, name="add_favorite"),
    path("favorites/<int:recipe_id>/", views.delete_favorites,
         name="delete_favorite"),

    path("shop_list/", views.shop_list, name="shop_list"),
    path("shop_list/delete/<int:recipe_id>/", views.shop_list_delete,
         name="shop_list_delete"),
    path("shop_list/get_pdf/", views.send_pdf, name="shop_list_send_pdf"),
    path("shop_list/delete_all/", views.shop_list_delete_all,
         name="shop_list_delete_all"),

    path("history/", views.history_view, name="history_view"),
    path("history/<int:history_id>/", views.recover_shop_list,
         name="recover_shop_list"),
    path("history/delete/<int:history_id>/", views.delete_history,
         name="delete_history"),

    path("purchases/", views.add_purchases, name="add_purchases"),
    path("purchases/<int:recipe_id>/", views.delete_purchases,
         name="delete_purchases"),

    path("subscriptions/", views.create_subscriptions,
         name="create_subscriptions"),
    path("subscriptions/<int:author_id>/", views.delete_subscriptions,
         name="delete_subscriptions"),

    path("ingredients/", views.get_ingredients, name="get_ingredients"),

]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Tag(models.Model):
    RED = 'red'
    BLUE = 'blue'
    BLACK = 'black'
    ORANGE = 'orange'
    GREEN = 'green'
    YELLOW = 'yellow'
    CYAN = 'cyan'
    PURPLE = 'purple'
    VIOLET = 'violet'
    COLORS = (
        (RED, 'red'),
        (BLUE, 'blue'),
        (BLACK, 'black'),
        (ORANGE, 'orange'),
        (GREEN, 'green'),
        (YELLOW, 'yellow'),
        (CYAN, 'cyan'),
        (PURPLE, 'purple'),
        (VIOLET, 'violet'),
    )
    title = models.CharField('Название', unique=True, max_length=15)
    style = models.CharField('Стиль', max_length=30, null=False,
                             default='green', choices=COLORS)
    slug = models.SlugField('Слаг', unique=True, max_length=15)

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    title = models.CharField('Название', db_index=True, max_length=100)
    dimension = models.CharField('Единицы измерения', max_length=15)

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self):
        return self.title


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор'
    )
    title = models.CharField('Название', unique=True, max_length=200)
    description = models.TextField('Описание рецепта', blank=False)
    image = models.ImageField('Картинка', upload_to='recipes/')
    ingredients = models.ManyToManyField(
        'IngredientAmount',
        verbose_name='Ингридиент',
        related_name='ingredient_amount',

    )
    tags = models.ManyToManyField(
        Tag, related_name='recipe_tags', verbose_name='Тэги рецепта',
    )
    duration = models.PositiveSmallIntegerField()
    slug = models.SlugField(unique=True, blank=True, null=True)
    pub_date = models.DateTimeField(
        'Дата создания', auto_now_add=True,
        db_index=True,
    )

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ['-pub_date']

    def __str__(self):
        return self.title


class IngredientAmount(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.DO_NOTHING)
    amount = models.IntegerField()

    class Meta:
        verbose_name = 'Ингредиент с количеством'
        verbose_name_plural = 'Ингредиенты с количеством'

    def __str__(self):
        return f'{self.ingredient} - {self.amount}'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique follow')
        ]


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipes = models.ManyToManyField(
        Recipe,
        related_name='favorites',
        verbose_name='Избранные рецепты'
    )

    class Meta:
        verbose_name = 'Избранный рецепт'
        verbose_name_plural = 'Избранные рецепты'

    def __str__(self):
        return f"{self.user}'s  recipes"


class ShopList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    recipes = models.ManyToManyField(
        Recipe,
        related_name='shop_list',
        verbose_name='Список покупок'
    )

    class Meta:
        verbose_name = 'Список покупок'
        verbose_name_plural = 'Списки покупок'

    def __str__(self):
        return f"{self.user}'s - ShopList"


class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(
        'Дата создания', auto_now_add=True,
        db_index=True,
    )
    recipes = models.ManyToManyField(
        Recipe,
        related_name='history',
        verbose_name='История покупок'
    )

    class Meta:
        verbose_name = 'История покупок'
        verbose_name_plural = 'Истории покупок'

    def __str__(self):
        return f"{self.user}'s - History"

recipes/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = (
            'title', 'tags', 'duration', 'description', 'image'
        )

recipes/views.py
import datetime as dt
import io
import json

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import FileResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from foodgram.settings import VISIBLE_RECIPES
from recipes.forms import RecipeForm
from recipes.handlers import (generate_pdf, generate_tag_links,
                              get_form_ingredients, get_recipe_ingredients,
                              tags_handler)
from recipes.models import (Favorite, Follow, History, Ingredient,
                            IngredientAmount, Recipe, ShopList, Tag, User)


def index(request):
    search = request.GET.getlist('search')
    tags = Tag.objects.all()
    passed_tags = tags_handler(search)
    tags_links = generate_tag_links(passed_tags)
    tags_id = tags.filter(slug__in=passed_tags).values_list('id', flat=True)
    recipes = Recipe.objects.filter(tags__in=tags_id).distinct()

    paginator = Paginator(recipes, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(
        request,
        template_name='index.html',
        context={
            'passed_tags': passed_tags,
            'tags_links': tags_links,
            'page': page,
            'paginator': paginator
        },
    )


@login_required
def my_follow(request, username):
    follows = Follow.objects.filter(user=request.user)
    paginator = Paginator(follows, 3)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        template_name='myFollow.html',
        context={
            'visible': VISIBLE_RECIPES,
            'page': page,
            'paginator': paginator
        },
    )


def new_recipe(request):
    form = RecipeForm(request.POST or None, files=request.FILES or None)
    ingredients = get_form_ingredients(request)
    if form.is_valid() and ingredients:
        recipe = form.save(commit=False)
        recipe.author = request.user
        form.save()
        passed_tags = request.POST.getlist('tags')
        for tag_id in passed_tags:
            tag = get_object_or_404(Tag, id=tag_id)
            recipe.tags.add(tag)

        for ing_id, values in ingredients.items():
            title, amount, units = values
            ingredient = Ingredient.objects.get_or_create(
                title=title, dimension=units)[0]
            new_ingredient = IngredientAmount.objects.get_or_create(
                ingredient=ingredient,
                amount=amount)[0]
            recipe.ingredients.add(new_ingredient)
        form.save_m2m()
        return redirect('index')
    if request.method == 'POST' and not ingredients:
        form.add_error(None, 'Обязательное поле.')
    return render(
        request,
        template_name='formRecipe.html',
        context={
            'form': form,
        }
    )


@login_required
def change_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    user = request.user
    author = recipe.author
    if user != author:
        return redirect('recipe_view', recipe_id=recipe_id)
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe
    )
    ingredients = get_form_ingredients(request)
    if form.is_valid():
        form.save()
        recipe.ingredients.clear()
        for ing_id, values in ingredients.items():
            title, *specifications = values
            if specifications:
                ingredient = Ingredient.objects.get_or_create(
                    title=title, dimension=specifications[1])[0]
                new_ingredient = IngredientAmount.objects.get_or_create(
                    ingredient=ingredient, amount=specifications[0])[0]
            else:
                new_ingredient = IngredientAmount.objects.get_or_create(
                    id=ing_id)[0]
            recipe.ingredients.add(new_ingredient)

        return redirect('recipe_view', recipe_id=recipe_id)

    if request.method == 'POST' and not ingredients:
        form.add_error(None, 'Обязательное поле.')
    recipe_tags = recipe.tags.all()
    ingredients = recipe.ingredients.all()
    return render(request, 'formChangeRecipe.html', {
        'form': form,
        'recipe': recipe,
        'ingredients': ingredients,
        'recipe_tags': recipe_tags
    })


@login_required
def delete_recipe(request, recipe_id):
    Recipe.objects.filter(author=request.user, id=recipe_id).delete()
    return redirect('index')


@login_required
def favorite(request):
    search = request.GET.getlist('search')

    fav_recipes_ids = Favorite.objects.get_or_create(
        user=request.user)[0].recipes.values_list('id', flat=True)
    favorite_recipes = Recipe.objects.filter(id__in=fav_recipes_ids)

    tags = Tag.objects.all()
    passed_tags = tags_handler(search)
    tags_links = generate_tag_links(passed_tags)
    tags_id = tags.filter(slug__in=passed_tags).values_list('id', flat=True)

    result_recipes = favorite_recipes.filter(
        tags__in=tags_id).distinct().order_by('-pub_date')

    paginator = Paginator(result_recipes, 3)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        template_name='favorite.html',
        context={
            'passed_tags': passed_tags,
            'tags_links': tags_links,
            'page': page,
            'paginator': paginator
        },
    )


@login_required
def shop_list(request):
    user = request.user
    my_shop_list = ShopList.objects.filter(user=user.id).first()
    if my_shop_list:
        recipes = my_shop_list.recipes.all()
    else:
        recipes = None
    return render(
        request,
        template_name='shopList.html', context={'recipes': recipes})


@login_required
def shop_list_delete(request, recipe_id):
    user = request.user
    my_shop_list = ShopList.objects.get_or_create(user=user.id)[0]
    current_recipe = get_object_or_404(Recipe, id=recipe_id)
    my_shop_list.recipes.remove(current_recipe)
    return redirect('shop_list')


def shop_list_delete_all(request):
    my_shop_list = get_object_or_404(ShopList, user=request.user)
    if my_shop_list.recipes:
        my_shop_list.recipes.clear()
        return redirect('shop_list')


@login_required
def send_pdf(request):
    my_shop_list = get_object_or_404(ShopList, user=request.user)
    recipes = my_shop_list.recipes.all()
    ingredients = get_recipe_ingredients(recipes)
    buffer = io.BytesIO()
    generate_pdf(ingredients, buffer)
    buffer.seek(0)
    date_str = dt.datetime.now().strftime('%d-%m-%Y_%H-%M')
    if recipes:
        my_history = History.objects.create(user=request.user)
        for recipe in recipes:
            my_history.recipes.add(recipe)
    return FileResponse(buffer, as_attachment=True,
                        filename=f'shoplist_{date_str}.pdf')


def author_recipes(request, author):
    search = request.GET.getlist('search')
    tags = Tag.objects.all()
    passed_tags = tags_handler(search)
    tags_links = generate_tag_links(passed_tags)
    tags_id = tags.filter(slug__in=passed_tags).values_list('id', flat=True)
    author = get_object_or_404(User, username=author)
    recipes = Recipe.objects.filter(author=author).filter(
        tags__in=tags_id).distinct().order_by(
        '-pub_date')
    paginator = Paginator(recipes, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(
        request,
        template_name='authorRecipe.html',
        context={
            'author': author,
            'passed_tags': passed_tags,
            'tags_links': tags_links,
            'page': page,
            'paginator': paginator
        },
    )


@login_required
def recipe_view(request, recipe_id):
    current_recipe = get_object_or_404(Recipe, id=recipe_id)
    return render(
        request,
        template_name='singlePage.html',
        context={'recipe': current_recipe,
                 },
    )


@login_required
def history_view(request):
    my_history = History.objects.filter(user=request.user.id).order_by(
        '-pub_date')
    paginator = Paginator(my_history, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        template_name='History.html',
        context={'page': page,
                 'paginator': paginator
                 },
    )


@login_required
def recover_shop_list(request, history_id):
    my_history = get_object_or_404(History, pk=history_id)
    my_shop_list = get_object_or_404(ShopList, user=request.user)
    for recipe in my_history.recipes.all():
        my_shop_list.recipes.add(recipe)
    return redirect(
        'shop_list'
    )


@login_required
def delete_history(request, history_id):
    my_history = get_object_or_404(History, pk=history_id)
    my_history.delete()
    return redirect(
        'history_view'
    )


@login_required
def add_purchases(request):
    if request.method == "POST":
        recipe_id = json.loads(request.body).get('id')
        recipe = get_object_or_404(Recipe, id=recipe_id)
        my_shop_list = ShopList.objects.get_or_create(user=request.user)[0]
        my_shop_list.recipes.add(recipe)
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})


@login_required
def delete_purchases(request, recipe_id):
    if request.method == "DELETE":
        my_shop_list = get_object_or_404(ShopList, user=request.user)
        my_shop_list.recipes.remove(recipe_id)
        return JsonResponse(
            {'success': True}) if my_shop_list else JsonResponse(
            {'success': False})
    return JsonResponse({'success': True})


@login_required
def create_subscriptions(request):
    if request.method == "POST":
        author_id = json.loads(request.body).get('id')

recipes/templates/History.html
{% extends "base.html" %}
{% block title %}История покупок{% endblock %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}
{% block content %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">История покупок</h1>
    </div>
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for item in page %}
            <li class="shopping-list__item" >
                    <h3 class="recipe__title">{{ item.pub_date }}</h3>
                    <div class=" recipe_reverse">
                        {% for recipe in item.recipes.all %}
                            <p class="single-card__section-item">{{ recipe.title }}</p>
                        {% endfor %}
                    </div>

                <a href="{% url 'recover_shop_list' item.id %}" class="shopping-list__button link" title="Расширит список покупок данными рецптами.">Восстановить</a>

                <a href="{% url 'delete_history' item.id %}" class="shopping-list__button link">Удалить</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% if page.has_other_pages %}
        {% include "includes/paginator.html" with items=page paginator=paginator%}
    {% endif %}
</main>
{% endblock %}

recipes/templates/formChangeRecipe.html
{% extends "base.html" %}
{% block title %}Редактирование рецепта{% endblock %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}
{% block content %}
{% csrf_token %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Редактирование рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_title" name="title" class="form__input" value="{{ recipe.title }}">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag in tags %}
                            <div class="tags__item">
                                <input type="checkbox" name="tags" value="{{ tag.id }}" id="id_{{ tag.slug }}"
                                       class="tags__checkbox tags__checkbox_style_{{ tag.style }}" {% if tag in recipe_tags %} checked {% endif %}>
                            <label for="id_{{ tag.slug }}" class="tags__label">{{ tag.title }}</label>
                        </div>
                        {% endfor %}
                    </div>
                    <span class="form__error">{{ form.tags.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>

                    <div class="form__field-group-ingredientes-container">
                        {% for ing in recipe.ingredients.all %}
                            <div class="form__field-item-ingredient"
                                 id="{{ ing.id }}">
                                <span> {{ ing.ingredient.title }} {{ ing.amount }} {{ ing.ingredient.dimension }}</span>
                                <span class="form__field-item-delete"></span>
                                <input id="nameIngredient_{{ing.id}}"
                                       name="nameIngredient_{{ ing.id }}"
                                       type="hidden"
                                       value="{{ ing.ingredient.title }}">
                            </div>
                        {% endfor %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_duration" name="duration" class="form__input" value="{{ recipe.duration }}">
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description" rows="8" class="form__textarea">
                        {{ recipe.description }}
                    </textarea>
                    <span class="form__error">{{ form.description.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <label for="id_file" class="form__file-button">Выбрать файл</label>
                    <input type="file" class="form__file" name="image" id="id_file" >
                    <span class="form__error"></span>
                </div>
            </div>

            {% if recipe.image %}
                <div class="form__group">
                    <span class="form__label">Текущее</span>
                    <div class="form__field-group">
                        <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" style="width:100px;">
                    </div>
                </div>
            {% endif %}
            <div class="form__footer">
                <button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em" href="{% url 'delete_recipe' recipe.id %}" class="form__ingredient-link">Удалить</a>
            </div>
        </form>
    </div>
</main>
{% endblock %}

{% block js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static '/js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

recipes/templates/formRecipe.html
{% extends "base.html" %}
{% block title %}Создание рецепта{% endblock %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}
{% block content %}
{% csrf_token %}
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_title" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_title" name="title"
                           class="form__input" value="{{ recipe.title }}">
                    {% if form.title.errors %}
                        <span class="form__error">
                            {{ form.title.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag in tags %}
                            <div class="tags__item">
                                <input type="checkbox" name="tags" value="{{ tag.id }}" id="id_{{ tag.slug }}" class="tags__checkbox tags__checkbox_style_{{ tag.style }}">
                                <label for="id_{{ tag.slug }}" class="tags__label">{{ tag.title }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    {% if form.tags.errors %}
                        <span class="form__error">{{ form.tags.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">

                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    {% if form.non_field_errors %}
                        <span class="form__error">
                            {{ form.non_field_errors }}
                        </span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_time" name="duration"
                           class="form__input" value="{{ recipe.duration }}">
                    <label for="id_time" class="form__label">минут</label>
                    {% if form.duration.errors %}
                        <span class="form__error">{{ form.duration.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description"
                              rows="8" class="form__textarea">
                        {{ recipe.description }}
                    </textarea>
                    {% if form.description.errors %}
                        <span class="form__error">
                            {{ form.description.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <input type="file" name="image" id="id_file"
                           value="{{ recipe.image }}">
                    {% if form.image.errors %}
                        <span class="form__error">
                            {{ form.image.errors|striptags }}
                        </span>
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать рецепт</button>
            </div>
        </form>
    </div>
</main>
{% endblock %}

{% block js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static '/js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}